### PR TITLE
Fix Cube Search Filter

### PR DESCRIPTION
**Pull request by AtzaMan**
Cube Recipies Search Filter now correctly returns multiple recipes in results instead of the first one found

### CODE REVIEW

**Review by CollinHerber — COMMENTED** [review]
LGTM
Missing vite build files though for the docs folder, can you commit those after doing `pnpm run build`

**Comment by AtzaMan** [comment]
This is the as is fork of the master branch on my GitHub account, with changes made on one file only, and then commited back here as Pull Request.
I never ran any build on this codebase, nor should I?
This is just the base code, no builds, dependancies or additional files to run the application.
I assume all codebase changes need a rebuild on the deployment side, for example a web server.

**Comment by CollinHerber** [comment]
> This is the as is fork of the master branch on my GitHub account, with changes made on one file only, and then commited back here as Pull Request. I never ran any build on this codebase, nor should I? This is just the base code, no builds, dependancies or additional files to run the application. I assume all codebase changes need a rebuild on the deployment side, for example a web server.

Github hosts the website from the docs folder 
When you run pnpm run build you update the docs files. All I want is for you to run pnpm run build and commit those changes as well.

**Comment by AtzaMan** [comment]
> > This is the as is fork of the master branch on my GitHub account, with changes made on one file only, and then commited back here as Pull Request. I never ran any build on this codebase, nor should I? This is just the base code, no builds, dependancies or additional files to run the application. I assume all codebase changes need a rebuild on the deployment side, for example a web server.
> 
> Github hosts the website from the docs folder When you run pnpm run build you update the docs files. All I want is for you to run pnpm run build and commit those changes as well.

I see. The docs folder, upon building the application, is used as a staging ground for web hosting. This is a different deployment scenario. I can see how merged and then built changes made here can enable automation.

**Comment by CollinHerber** [comment]
Yes a simple github action to run `pnpm run build` and then commit those changes on pushes to master will be added in the near future.

**Comment by CollinHerber** [comment]
I am going to just merge this and do it myself

**Pull request merged**
