### PR TITLE
Talonrage Docs Sets

### PR DESCRIPTION
**Pull request by AtzaMan**
Fixed the Talonrage Docs Sets page, Set1-Set25 dropmenu titles to correctly indicate the set names found in game's item-names.json file.

### CODE REVIEW

**Comment by CollinHerber** [comment]
You have a conflict. Please resolve.

**Comment by AtzaMan** [comment]
> You have a conflict. Please resolve.

Please suggest on how to resolve the conflict that arises when each time your run pnpm build?
The build itself generates different JS files names everyone.

**Comment by CollinHerber** [comment]
> > You have a conflict. Please resolve.
> 
> Please suggest on how to resolve the conflict that arises each time your run pnpm build? The build itself generates different JavaScript file names everytime.

You branched off the main branch without pulling the latest changes. This is why you see this. No different than any other repo

**Comment by AtzaMan** [comment]
Resolved conflict.

**Review by CollinHerber — APPROVED** [review]

**Pull request merged**
